name: 'KyberCheck Scanner'
description: 'Scan codebase for quantum-vulnerable cryptography'
author: 'KyberCheck'

branding:
  icon: 'shield'
  color: 'blue'

inputs:
  api-key:
    description: 'KyberCheck API Key'
    required: true
  scan-id:
    description: 'Scan ID from KyberCheck dashboard (for website-triggered scans)'
    required: false
  dispatch-token:
    description: 'Dispatch token for authenticated result submission (provided by KyberCheck backend)'
    required: false
  api-url:
    description: 'API URL for results submission'
    required: false
    default: 'https://kybercheck.com'
  path:
    description: 'Path to scan'
    required: false
    default: '.'
  exclude:
    description: 'Comma-separated glob patterns to exclude from scanning'
    required: false
  languages:
    description: 'Comma-separated list of languages to scan'
    required: false
  fail-on-critical:
    description: 'Fail build on critical vulnerabilities'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Install KyberCheck CLI
      shell: bash
      run: |
        echo "⬇️ Downloading KyberCheck CLI..."
        DOWNLOAD_URL="https://github.com/KyberCheck/kybercheck-cli/releases/latest/download/kybercheck-linux-amd64"
        curl -fsSL "$DOWNLOAD_URL" -o /usr/local/bin/kybercheck || {
          echo "Binary download failed, falling back to cargo install..."
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source "$HOME/.cargo/env"
          cargo install kybercheck --force
        }
        chmod +x /usr/local/bin/kybercheck
        echo "✅ KyberCheck CLI installed successfully."

    - name: Run KyberCheck Scan
      shell: bash
      env:
        KYBERCHECK_API_KEY: ${{ inputs.api-key }}
      run: |
        echo "========================================"
        echo "🔍 KyberCheck Quantum Vulnerability Scan"
        echo "========================================"
        echo ""
        echo "📋 Configuration:"
        echo "  Path: ${{ inputs.path }}"
        echo "  API URL: ${{ inputs.api-url }}"
        echo "  Scan ID: ${{ inputs.scan-id }}"
        echo "  Exclude: ${{ inputs.exclude }}"
        echo "  Languages: ${{ inputs.languages }}"
        echo "  API Key: ${KYBERCHECK_API_KEY:0:10}..."
        echo ""

        CMD="kybercheck scan ${{ inputs.path }}"

        # Pass scan-id if provided
        if [ -n "${{ inputs.scan-id }}" ]; then
          CMD="$CMD --scan-id ${{ inputs.scan-id }}"
        fi

        # Pass dispatch token if provided (required for submitting results to dashboard)
        if [ -n "${{ inputs.dispatch-token }}" ]; then
          CMD="$CMD --dispatch-token ${{ inputs.dispatch-token }}"
        else
          # No dispatch token — run local-only scan (don't submit to API)
          CMD="$CMD --no-submit"
        fi

        # Pass API URL
        if [ -n "${{ inputs.api-url }}" ]; then
          CMD="$CMD --api-url ${{ inputs.api-url }}"
        fi

        # Pass exclude patterns
        if [ -n "${{ inputs.exclude }}" ]; then
          CMD="$CMD --exclude \"${{ inputs.exclude }}\""
        fi

        # Pass language filter
        if [ -n "${{ inputs.languages }}" ]; then
          CMD="$CMD --languages \"${{ inputs.languages }}\""
        fi

        # Fail on vulnerabilities if requested
        if [ "${{ inputs.fail-on-critical }}" = "true" ]; then
          CMD="$CMD --fail-on-vuln"
        fi

        echo "🚀 Executing: $CMD"
        echo "========================================"
        echo ""

        eval $CMD

        echo ""
        echo "========================================"
        echo "✅ Scan complete!"
        echo "========================================"