name: 'KyberCheck Scanner'
description: 'Scan codebase for quantum-vulnerable cryptography'
author: 'KyberCheck'

branding:
  icon: 'shield'
  color: 'blue'

inputs:
  api-key:
    description: 'KyberCheck API Key'
    required: true
  scan-id:
    description: 'Scan ID from KyberCheck dashboard (for website-triggered scans)'
    required: false
  dispatch-token:
    description: 'Dispatch token for authenticated result submission (provided by KyberCheck backend)'
    required: false
  api-url:
    description: 'API URL for results submission'
    required: false
    default: 'https://kybercheck.com'
  path:
    description: 'Path to scan'
    required: false
    default: '.'
  exclude:
    description: 'Comma-separated glob patterns to exclude from scanning'
    required: false
  languages:
    description: 'Comma-separated list of languages to scan'
    required: false
  fail-on-critical:
    description: 'Fail build on critical vulnerabilities'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Install KyberCheck CLI
      shell: bash
      run: |
        echo "⬇️ Downloading KyberCheck CLI..."
        DOWNLOAD_URL="https://github.com/KyberCheck/kybercheck-cli/releases/latest/download/kybercheck-linux-amd64"
        curl -fsSL "$DOWNLOAD_URL" -o /usr/local/bin/kybercheck || {
          echo "Binary download failed, falling back to cargo install..."
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source "$HOME/.cargo/env"
          cargo install kybercheck --force
        }
        chmod +x /usr/local/bin/kybercheck
        echo "✅ KyberCheck CLI installed successfully."

    - name: Prepare scan scope
      id: scope
      shell: bash
      run: |
        if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
          echo "📋 PR detected — scanning only changed files"
          
          # Ensure base branch is available for diff
          git fetch origin "$GITHUB_BASE_REF" --quiet 2>/dev/null || true
          
          # Get list of changed files (Added, Copied, Modified, Renamed)
          CHANGED_FILES=$(git diff --name-only --diff-filter=ACMR "origin/$GITHUB_BASE_REF"...HEAD 2>/dev/null || echo "")
          
          if [ -z "$CHANGED_FILES" ]; then
            echo "⚠️ No changed files detected, falling back to full scan"
            echo "scan_path=${{ inputs.path }}" >> "$GITHUB_OUTPUT"
          else
            # Create temp directory with only changed files (preserving directory structure)
            SCAN_DIR=$(mktemp -d)
            echo "$CHANGED_FILES" | while IFS= read -r file; do
              if [ -f "$file" ]; then
                mkdir -p "$SCAN_DIR/$(dirname "$file")"
                cp "$file" "$SCAN_DIR/$file"
              fi
            done
            
            FILE_COUNT=$(echo "$CHANGED_FILES" | wc -l | tr -d ' ')
            echo "  Found $FILE_COUNT changed files"
            echo "scan_path=$SCAN_DIR" >> "$GITHUB_OUTPUT"
          fi
        else
          echo "📋 Push/schedule event — scanning full repository"
          echo "scan_path=${{ inputs.path }}" >> "$GITHUB_OUTPUT"
        fi

    - name: Run KyberCheck Scan
      shell: bash
      env:
        KYBERCHECK_API_KEY: ${{ inputs.api-key }}
      run: |
        echo "========================================"
        echo "🔍 KyberCheck Quantum Vulnerability Scan"
        echo "========================================"
        echo ""
        echo "📋 Configuration:"
        echo "  Path: ${{ steps.scope.outputs.scan_path }}"
        echo "  API URL: ${{ inputs.api-url }}"
        echo "  Scan ID: ${{ inputs.scan-id }}"
        echo "  Exclude: ${{ inputs.exclude }}"
        echo "  Languages: ${{ inputs.languages }}"
        echo "  API Key: ${KYBERCHECK_API_KEY:0:10}..."
        echo ""

        CMD="kybercheck scan ${{ steps.scope.outputs.scan_path }}"

        # Pass scan-id if provided
        if [ -n "${{ inputs.scan-id }}" ]; then
          CMD="$CMD --scan-id ${{ inputs.scan-id }}"
        fi

        # Pass dispatch token if provided (required for submitting results to dashboard)
        if [ -n "${{ inputs.dispatch-token }}" ]; then
          CMD="$CMD --dispatch-token ${{ inputs.dispatch-token }}"
        else
          # No dispatch token — run local-only scan (don't submit to API)
          CMD="$CMD --no-submit"
        fi

        # Pass API URL
        if [ -n "${{ inputs.api-url }}" ]; then
          CMD="$CMD --api-url ${{ inputs.api-url }}"
        fi

        # Pass exclude patterns
        if [ -n "${{ inputs.exclude }}" ]; then
          CMD="$CMD --exclude \"${{ inputs.exclude }}\""
        fi

        # Pass language filter
        if [ -n "${{ inputs.languages }}" ]; then
          CMD="$CMD --languages \"${{ inputs.languages }}\""
        fi

        # Fail on vulnerabilities if requested
        if [ "${{ inputs.fail-on-critical }}" = "true" ]; then
          CMD="$CMD --fail-on-vuln"
        fi

        echo "🚀 Executing: $CMD"
        echo "========================================"
        echo ""

        eval $CMD

        echo ""
        echo "========================================"
        echo "✅ Scan complete!"
        echo "========================================"